// Fixed, anonymized source fixtures. External-I/O examples are only analyzed;
// the self-contained objectLoop162 can also run in a real kernel.
export const objectLoop162 =
  'let value=null;\nfor(let p=0;p<2;p++){\nfor(let attempt=0;attempt<2;attempt++){\ntry{value=JSON.stringify({page:p,size:100});}catch(e){value=null;}\n}\n}\nreturn value;'
export const objectLoop184 =
  'let value=null; for(let p=0;p<count;p++){ for(let attempt=0;attempt<2;attempt++){ try { value=await host.mcp("data","list",{page:p,size:100}); } catch(e){value=null;} } } return value;'
export const catalogPagination =
  'const fs = require(\'node:fs\');\nconst path = require(\'node:path\');\nconst all = [...(samplePage1.results || [])];\nconst total = samplePage1.total;\nconst failed = [];\nfor (let p = 2; p <= Math.ceil(total / 100); p++) {\n  let got = null;\n  for (let attempt = 0; attempt < 2 && !got; attempt++) {\n    try {\n      const r = await host.mcp("example-catalog", "list_datasets", { page: p, page_size: 100 });\n      got = r.results || [];\n    } catch (e) {\n      if (attempt === 1) failed.push(p);\n      await new Promise(r => setTimeout(r, 1500));\n    }\n  }\n  if (got) all.push(...got);\n}\nglobalThis.sampleDatasets = all;\nglobalThis.sampleFailedPages = failed;\nconst cells = all.map(d => d.cell_count).filter(v => typeof v === "number" && v > 0).sort((a, b) => a - b);\nconst recs = all.map(d => ({\n  dataset_id: d.dataset_id, dataset_version_id: d.dataset_version_id,\n  collection_id: d.collection_id, collection_name: d.collection_name, collection_doi: d.collection_doi,\n  title: d.title, cell_count: d.cell_count, primary_cell_count: d.primary_cell_count,\n  schema_version: d.schema_version, published_at: d.published_at, revised_at: d.revised_at,\n  organism: (d.organism || []).map(x => x.label).join(" | "),\n  tissue: (d.tissue || []).map(x => x.label).join(" | "),\n  disease: (d.disease || []).map(x => x.label).join(" | "),\n  assay: (d.assay || []).map(x => x.label).join(" | "),\n}));\nconst esc = (v) => { const s = v === null || v === undefined ? "" : String(v); return /[",\\n]/.test(s) ? \'"\' + s.replace(/"/g, \'""\') + \'"\' : s; };\nconst csv = [Object.keys(recs[0]).join(","), ...recs.map(r => Object.values(r).map(esc).join(","))].join("\\n") + "\\n";\nconst out = path.join(process.env.OPEN_SCIENCE_HANDOFF_DIR, "sample_datasets.csv");\nfs.writeFileSync(out, csv, "utf8");\nglobalThis.sampleCsvPath = out;\nreturn {\n  fetched: all.length, expected_total: total, failed_pages: failed, csv_mb: +(csv.length / 1e6).toFixed(2),\n  n_with_cells: cells.length, total_cells_millions: +(cells.reduce((a,b)=>a+b,0)/1e6).toFixed(1),\n  median_cells: cells[Math.floor(cells.length/2)], max_cells: cells[cells.length-1],\n};'
export const fileMetadataPagination =
  'const fs=require("node:fs");const HD=process.env.OPEN_SCIENCE_HANDOFF_DIR;\nconst rows=fs.readFileSync(HD+"/input-plan.tsv","utf8").trim().split("\\n").map(l=>l.split("\\t"));\nconst names=rows.filter(r=>r[0]==="expr").map(r=>r[3]);\nlet hits=[];\nfor(let i=0;i<names.length;i+=50){\n  const ch=names.slice(i,i+50);\n  const body={filters:{op:"in",content:{field:"files.file_name",value:ch}},\n              fields:"file_id,file_name,md5sum,file_size,cases.submitter_id,cases.project_id",format:"JSON",size:"500"};\n  for(let att=0;att<3;att++){\n    try{\n      const r=await fetch("https://data.example.invalid/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});\n      const j=await r.json(); hits=hits.concat(j.data.hits); break;\n    }catch(e){ if(att===2) throw e; }\n  }\n}\nconst map={};\nfor(const h of hits){ map[h.file_name]={file_id:h.file_id,case:h.cases&&h.cases[0]?h.cases[0].submitter_id:null,project:h.cases&&h.cases[0]?h.cases[0].project_id:null,md5:h.md5sum,bytes:h.file_size}; }\nfs.writeFileSync(HD+"/record-map.json",JSON.stringify(map,null,1));\nglobalThis.recordMap=map;\nreturn {n_names:names.length, n_hits:hits.length, n_map:Object.keys(map).length, byProject:Object.values(map).reduce((a,m)=>{a[m.project]=(a[m.project]||0)+1;return a;},{})};'
